### ISSUE TITLE
Attribute 'error' is null when the error is thrown by the controller

### ISSUE THREAD

**Issue by Talha19** [mauriciolauffer/openui5-error-collector#16]
Hello @mauriciolauffer,

i have the problem that the attribute error is null when the error is raised by the ui5 controller.

For example.

`buttonPressed: function(){ 
            this.callSomeMethodWhichDoesNotExist();
        }
`

the method 'callSomeMethodWhichDoesNotExist' does not exist in the controller and I see the error stack in the browser console. But ui5ErrorCollector throws the following error:

`Uncaught TypeError: Cannot read properties of null (reading 'stack').
    at m (ui5ErrorCollector.min.js:1:642)
    at ui5ErrorCollector.min.js:1:2094`

it would be great if I could catch this kind of error as well.

Do you have any idea what the problem is?

thx and br
Talha Kalabalik

**Comment by mauriciolauffer** [comment]
@Talha19 could you share the json result from `ui5ErrorCollector.getErrors()`, pls?

![image](https://user-images.githubusercontent.com/443888/181178096-b017878b-b6e4-42b5-89b9-0d9aacad2d4a.png)

**Comment by Talha19** [comment]
Hey @mauriciolauffer,

the problem is fixed since yesterday. It war related to the property `crossorigin="anonymous"` in index.html.

`    <script id="sap-ui-bootstrap" 
        src="https://sapui5.netweaver.ondemand.com/1.92.0/resources/sap-ui-core.js" 
        data-sap-ui-libs="sap.m" 
        data-sap-ui-theme="sap_belize" 
        data-sap-ui-compatVersion="edge" 
        data-sap-ui-resourceroots='...'
        crossorigin="anonymous">
    </script>`

If this property is not provided, there is no error object and no stack available in ui5ErrorCollector.min.js.

however, it works now. 

thanks for your support and regards
